# Generated by Django 3.0.4 on 2020-03-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.TextField(default='Guest', max_length=40),
        ),
    ]
