# Generated by Django 3.0.4 on 2020-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20200313_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.TextField(max_length=40),
        ),
    ]
