# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#     - name: Lint with flake8
#       run: |
#         flake8
    - name: Start mysql
      run: |
          sudo service mysql start
    - name: Grant priviledges
      run: |
         mysql -u root --password=root --port 8889 -e "CREATE USER 'new_user'@'localhost';"
         mysql -u root --password=root --port 8889 -e "GRANT ALL PRIVILEGES ON test_properties.* TO 'new_user'@'localhost';"
    - name: Test with test
      run: |
        python manage.py test
    - name: Update remote
      run: |
        ssh -i "Basemera.pem" ubuntu@ec2-3-16-148-152.us-east-2.compute.amazonaws.com
        sudo git pull origin        

